### ISSUE TITLE
Gitlens as alternative

### ISSUE THREAD

**Issue by zchrissirhcz** [FinerKeysen/learngit#1]
Git commitzen 需要 npm 环境， 对于不做前端开发的人来说， npm 环境并没有 python 环境简单（直接anaconda），因此作为候选替代， 可以使用 gitlens。

https://www.cnblogs.com/zjutzz/p/14277253.html

**Comment by FinerKeysen** [comment]
@zchrissirhcz 谢谢建议。是的，commitzen配置上确实不如gitlens简洁快速；
早期学习的时候，若使用到npm，可以配合尝试体验一番。
另外对于大多开发场景而言，注重commit的使用规范更重要。
